#!/bin/bash

DIR="$(dirname "$0")/*"

ORIG_NAME="CCNativeExtensionTemplate"
MODULE_NAME="$1"

if [ -z "$MODULE_NAME" ];then
    cat<<EOF
usage: setup MODULE_NAME
EOF
exit 1
fi

UNDER_SCORE_NAME=$(echo $MODULE_NAME |  perl -pe 's/([A-Z])/_$1/g' | perl -pe 's/^_C_C_//g' | tr "A-Z" "a-z")
USER_NAME=$(git config --global user.name)
USER_EMAIL=$(git config --global user.email)
YEAR=$(date +%Y)

SUBDIRS=$(find $DIR -type d -maxdepth 0)
FILES=$(find $SUBDIRS -type f )
CMD="s/${ORIG_NAME}/${MODULE_NAME}/g"
perl -i.bak -pe "$CMD" $FILES
perl -i.bak -pe "$CMD" README_template.md
perl -i.bak -pe "s/native_extension_template/${UNDER_SCORE_NAME}/g" README_template.md
mv README_template.md README.md
perl -i.bak -pe "s/oke-ya.k.k/${USER_NAME}<$USER_EMAIL>/g" LICENSE.txt
perl -i.bak -pe "s/2016/$YEAR/g" LICENSE.txt
find . -name '*.bak' -delete

FILES=$(find $SUBDIRS -name ${ORIG_NAME}*)
for f in $FILES;do
    DESTNAME=$(echo $f | sed -e $CMD)
    mv $f $DESTNAME
done
rm setup


